print('hello world!')
print('hai gais, selamat malam')
print('aku ada puisi sedikit')
print('how was ur day?')
print('LESGOWW')
print('tentang senja dengan segala aninditanya')
print('menyentuh kalbu bagai tirta airmata')
print('dan bagaikan binar dikala temaram')
print('datang sebagai singgahan ternyaman')
print('untuk nuraga baik lara maupun harsa')
print('kini, senja yang selalu dinantikan telah hirap')
print('hyang kini hanyalah menjadi sebuah akara')
print('yang memberikan sebuah wiyata')
print('bahwa anindita, hanyalah sementara dan berakhir menjadi suatu mala')